# Generated by Django 4.2.4 on 2023-08-31 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ContractDatabase', '0002_contract_created_at_contract_creator_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='content',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='last_updated',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='title',
        ),
    ]
