# Generated by Django 4.2.4 on 2023-08-31 04:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ContractDatabase', '0003_remove_contract_content_remove_contract_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='content',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contract',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
