# Generated by Django 4.2.4 on 2023-08-31 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ContractDatabase', '0004_contract_content_contract_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='content',
            field=models.TextField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='contract',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
